# Generated by Django 5.2.3 on 2025-06-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50, unique=True, verbose_name='Mes')),
                ('sales', models.IntegerField(verbose_name='Ventas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Dato de Venta Mensual',
                'verbose_name_plural': 'Datos de Ventas Mensuales',
                'ordering': ['created_at'],
            },
        ),
    ]
