# Generated by Django 5.2.3 on 2025-06-23 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecyclingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month_name', models.CharField(max_length=20, verbose_name='Mes')),
                ('material_type', models.CharField(max_length=100, verbose_name='Tipo de Material')),
                ('amount_recycled', models.FloatField(verbose_name='Cantidad Reciclada (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Dato de Reciclaje Mensual',
                'verbose_name_plural': 'Datos de Reciclaje Mensuales',
                'ordering': ['user__username', 'year', 'month_name', 'material_type'],
                'unique_together': {('user', 'year', 'month_name', 'material_type')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlySalesData',
        ),
    ]
